Acode-Foundation/Acode

- .github/workflows/main.yml
If you want cordova to build --release, change the BUILD_TYPE value to release at line 34
> Add a GitHub Action to automatically build the .apk on new pushes

- .github/workflows/main.yml
Now the commit title comes at the top and the commit comment at the end
> Change the caption format for telegram sending

- www/res/ace/src/snippets/c_cpp.js
Add more snippets if, ifelse, elseif etc.
> Add more snippets

- src/settings/editorSettings.js
Autosave prompt must take 0 as a value.
> A fix in Autosave Settings

- src/lang/de-de.json
> Update de-de.json to 1.6.0.235

- src/lib/projects.js
Added a deleteethod for deleting any project
> Added delete method in projects

- src/lang/zh-cn.json
- src/lang/zh-hant.json
> Update zh translation

- src/sidebarApps/index.js
Please test it Because I have added it according to my understanding of code i haven't tested. But i am sure that it will work.
> Added removeApp() method to sidebarApps api

- src/lang/pt-br.json
Brazil language update (pt-BR).
> Update pt-br.json ( português - Brasil )

- readme.md
Added telegram and discord community badge in repo readme
> Added Community badge in repo

- src/lib/constants.js
- src/lib/openFolder.js
- src/pages/fileBrowser/fileBrowser.js
- src/utils/helpers.js
Enable creation of multiple nested files and folders from sidebar or file browser
Note: This feature is not supported on FTP/SFTP.
> Nested File/Folder creation

- src/pages/plugin/plugin.view.js
- src/pages/plugins/item.js
- src/sidebarApps/extensions/index.js
- src/utils/helpers.js
- Improved and Easily readable download counts
- In sidebar extension tab , Now it will also show downloads counts
> Improved Download Counts

- src/lib/commands.js
Fixed **save all changes** to do its work as it should.
> fix: Fixed `save all changes` option(#1008)

- src/pages/plugins/plugins.js
It because in case of image data context menu starts crashing and There is no such use of that
> removed auto paste of url on plugin page

- src/styles/page.scss
> fixed weird spacing issue on header #925

- src/fileSystem/sftp.js
> fix: file listing in sftp

- src/ace/colorView.js
> Svg color preview

- src/pages/about/about.hbs
- src/pages/about/about.scss
- www/index.html
> [!NOTE]
> I'm using catppuccin mocha theme
> feat: improved about page

- config.xml
- package-lock.json
- package.json
- src/lib/installPlugin.js
- src/sidebarApps/extensions/index.js
- src/sidebarApps/extensions/style.scss
- add cordova http plugin to do http requests without any cors issue
- add rebuild icon in sidebar for local plugin to easily reinstall it
- fixed remote plugin installation with ip
> feat: plugin rebuild option for local plugins

- src/components/settingsPage.js
- more specific selectors.
- more code readability.
> feat: add id for settings page

- src/plugins/ftp/plugin.xml
- src/plugins/ftp/src/android/com/foxdebug/ftp/Ftp.java
- add support for emoji
- add support for symlink
- better handling of video, image, etc
- show names instead of path
> improved ftp client

- src/pages/plugins/item.js
- src/pages/plugins/plugins.scss
- now it shows all basic info in list view
> feat: improved plugins page ui

- src/pages/changelog/style.scss
- src/utils/helpers.js
> Fix sftp sidebar UI issue

- package.json
- src/lib/fonts.js
> remove invalid font

- package-lock.json
- src/lib/run.js
This PR resolves an issue where HTML files located in Termux directories would fail to preview due to incorrect path handling. The file URI is now properly processed to support Termux-specific paths.
> Fix: "File Not Found" error when previewing HTML files from a Termux directory

- src/lib/editorManager.js
> fix: handle edge case for `hideQuickTools` property

- src/lib/keyBindings.js
> fix: pagedown key issue in editor

- config.xml
> feat. open files with arbitrary extension names

- src/dialogs/prompt.js
> fix. keyboard shortcuts leaks into ace editor

- src/sidebarApps/extensions/index.js
> fix: only initiate iap stuff in case of paid plugin on sidebar

- src/ace/touchHandler.js
> Comment out column adjustment in touchHandler.js for weird selection

- src/handlers/intent.js
- src/lib/main.js
> feat: Improve handling of intents before files are restored on startup

- src/components/terminal/terminal.js
- src/components/terminal/terminalTouchSelection.js
- src/settings/terminalSettings.js
- fix: dont start selection in case of back gesture
- remove useless border-radius
- fix: improve terminal cursor positioning for mobile keyboard events
- fix: update terminal container background when theme changes
> some terminal related quality improvements

- src/lib/run.js
> fix. infinite loading

- src/lib/run.js
- Disable overlap detection for GitHub URIs to prevent path corruption (index.html becoming dex.html)
- Skip file stat operations for GitHub URIs to prevent 404 errors on missing files like
favicon.ico
> fix: resolve GitHub URI preview issues in server

- src/lib/keyBindings.js
> Add code formatter keybind

- src/settings/terminalSettings.js
> feat: take confirmation before uninstalling terminal

- src/plugins/browser/android/com/foxdebug/browser/Browser.java
> fix: browser download

- src/components/terminal/terminalDefaults.js
- src/components/terminal/terminalManager.js
- src/lib/fonts.js
- src/main.js
Followup for #1570
This pull request introduces persistent terminal session management. The main changes include adding logic to save, restore, and clean up terminal sessions, updating terminal defaults, and preloading terminal fonts for better UI consistency.
> Restore terminal tabs 

- src/components/terminal/terminalTouchSelection.css
- src/components/terminal/terminalTouchSelection.js
> style(terminal): Some touch selection handle enhancements

- src/lib/openFolder.js
- src/utils/helpers.js
Introduces handling for 'content://com.foxdebug.acode.documents/tree/' URIs alongside Termux SAF URIs in openFolder.js and helpers.js. This enables file operations and path resolution for Acode terminal public SAF providers, improving compatibility with additional terminal-backed storage providers.
> fix: support for Acode terminal SAF URIs

- package-lock.json
- package.json
- src/plugins/system/android/com/foxdebug/system/System.java
- src/plugins/system/www/plugin.js
- src/plugins/terminal/plugin.xml
- src/plugins/terminal/scripts/rm-wrapper.sh
- src/plugins/terminal/www/Terminal.js
> Fix: rm command
