.github/workflows/main.yml
It requires 4 github actions secrets:
1. `CHAT_ID`
The Telegram chat id of the chat where the bot will send the builds to
2. `BOT_TOKEN`
The Telegram bot token got from [@BotFather](https://t.me/botfather)
3. `KEYSTORE_ENCODED`
The base64-encoded .keystore content (you can use `base64 <FILE>` on CLI, replacing <FILE> with the proper file name)
4. `SIGNING_PROPERTIES`
The content to write to platforms/android/release-signing.properties. Example:
```
storeFile=acode.keystore
storeType=jks
keyAlias=alias
keyPassword=mypassword
storePassword=mypassword
```
Just don't touch storeFile, because the workflow will decode the KEYSTORE_ENCODED value and save to acode.keystore. If you didn't specify a keyPassword while generating the key, use the same value of storePassword (you may know, but it got …
=> Add support to signed release builds and add sending to Telegram

src/lib/editorManager.js, src/lib/handlers/selectword.js, src/lib/openFolder.js, src/pages/fileBrowser/fileBrowser.include.js
Why disabling the "Vibrate on tap" setting does not remove vibrations in some cases (like long tapping on a word to select it)? Vibrations sometimes can be very annoying. So much annoying that they can force a person to fix this bug-like behavior and make a pull-request :)
(sorry for the newlines at the end of files, they were automatically added by github's built-in editor)
=> Do not vibrate when vibration setting is turned off

src/lib/git.js, src/pages/info/info.js
This fix changes code regarding `res.statusText` in if statements.
This fixes #155, and an issue where commiting a file would give an empty error, but would still succeed.
=> Don't rely on res.statusText when checking github response status

package.json, src/components/WebComponents/components.js, src/components/commandPallete.js, src/components/dialogboxes/multiprompt.js, src/components/page.js
This PR should fix Webpack errors when compiling on Linux or other unix-based systems.
If applied, it should also resolve issue #410.
I've tested this PR on a containerized Debian Testing with node.js 14.17.6, so those changes should work on F-Droid build servers too.
Ps. I've added sass module to package.json, because without it, I had 72 errors about .sass files in Webpack on my different machine.
=> Fix Webpack errors in Linux and other unix-based systems

src/lib/acode.js
```js 
const options = acode.getFormatterFor(extensions);
```
[defaultFormatter.js#L14](https://github.com/deadlyjack/Acode/blob/main/src/settings/defaultFormatter.js#L14)
=> Fixing acode.getFormatterFor returns undefined

config.xml
This allows Acode to be registered as the default application to open more file types.
When using MiXplorer file browser in particular, it presents a list of apps to use to open any particular file based on its type, eg.
This PR extends the list of supported file types to suggest using acode for these files :-)
=> Register extra mime typea to open json, js, sh and xml files.

readme.md
This PR aims to enhance the user experience and provide comprehensive information to potential users and contributors.
=> Improving the style of the readme

src/handlers/quickTools.js
Legacy settings has a key call 'backwards' in search settings that cause it to override the input to always search backwards
Fixes #809.
Note:  it used to be like this before the search change, backwards key/value get set after the settings
eg settings:
```json
"search": {
"caseSensitive": false,
"regExp": false,
"wholeWord": false,
"backwards": true
},
```
broken by https://github.com/deadlyjack/Acode/commit/82d147f8676034afcf1caa4deba5143f0d43fd26#diff-b46b01d6ed020a238065127cc51634b279fee3fe600705414a2ad9ef20052914L266
before:
https://github.com/deadlyjack/Acode/blob/08f8bb21650c0489967baa1aa1af021155a90889/src/handlers/quickTools.js#L266-L272
after:
https://github.com/deadlyjack/Acode/blob/82d147f8676034afcf1caa4deba5143f0d43fd26/src/handlers/quickTools.js#L292-L298
this change the …
=> Fix quicktools searching issue

src/components/searchbar/index.js, src/lib/openFolder.js, src/pages/fileBrowser/fileBrowser.js, src/pages/plugins/plugins.js, src/utils/helpers.js
- Fixed bugs related to the search bar on the plugin page.
- The search bar will no longer close accidentally when clicking elsewhere on the screen.
- Enhanced search functionality to allow searching across all available plugins from "all" section of the plugin page.
- Resolved duplication issue related to the feature added in #989.
=> Fix search bar bugs, enhance search functionality, and resolve duplication issue

src/sidebarApps/extensions/index.js, src/sidebarApps/extensions/style.scss
This pr adds some quick action to installed plugins in sidebar.
Demo:
=> feat: Add more action menu in sidebar plugin

src/ace/colorView.js, src/ace/commands.js, src/components/palette/index.js, src/components/searchbar/index.js, src/components/settingsPage.js, src/lib/actionStack.js, src/lib/commands.js, src/lib/constants.js, src/lib/editorFile.js, src/lib/fileList.js, src/lib/installPlugin.js, src/lib/logger.js, src/lib/main.js, src/pages/fileBrowser/fileBrowser.js, src/pages/plugin/plugin.js, src/pages/plugins/plugins.js, src/sidebarApps/extensions/index.js, src/sidebarApps/searchInFiles/index.js, src/theme/list.js
- Logger system
- Removed some old `console.log` and `console.error` with logger api
- Added new log method to `window` object
- Now avoid using console logs instead use logger , so it will be easy to debug any bug
- Logging system is efficient and it automatically manages flushing of buffer and LRU algorithm to keep log file small and relevant 
- Search for "Open Log file" in command palette to open the log file in editor.
=> Implement Logger system

src/lib/installPlugin.js, src/lib/installState.js
=> Added install state for better update of plugins (#1026)

src/lib/acode.js
Trying to format a file after changing the syntax highlighting for the file does not format the file with the selected mode
=> fix: formatter ignoring selected mode for file

src/lib/checkPluginsUpdate.js
Attempts to Fix were All Plugins Statuses are not Fetched(if a promise rejects) Due to usage of 'Promise.all'(it rejects when any of the input's promises rejects, with this first rejection reason.)
=> fix(checkPluginsUpdate): Not All Plugins Status due to `Promise.all` Rejection

src/lib/editorManager.js
A simple solution for copying/cutting the current line if there are no selected text.
Closes #1082
We could also add an option to toggle this on and off.
=> feat: copy/cut current line on empty selection

src/lib/settings.js
Fixed serious startup lag when I opened PHP Laravel or Python venv projects.
=> Exclude python `venv` and php `vendor` folders to speedup startup

package.json, src/ace/commands.js, src/lib/commands.js, src/pages/plugin/plugin.js, src/sidebarApps/extensions/index.js, src/styles/markdown.scss, src/utils/helpers.js, www/index.html
- Added new command(`file explorer`) to open file manager
- Added copy button to code blocks on plugin page
- some error logging for debugging
- few markdown tweaks
=> minor fixes and tweaks

src/pages/plugin/plugin.view.js
add className for user name in plugin reviews
=> add className

res/android/mipmap-anydpi-v26/ic_launcher.xml, res/android/mipmap-anydpi-v26/ic_launcher_round.xml
Added monochrome icon for Android 13 "Themed icons" support.
=> Add monochrome icon

src/lib/installState.js
I ran into an issues while updating a plugin.
The previous install had `readme.md` among its file while the update had `README.md` among its file. The `README.md` file was deleted becaused android sees the two file to be the same but InstallState sees them as different
=> updated install state to reflect fs behaviour of android

src/lib/loadPlugins.js, src/lib/main.js
=> fix: clean broken or half installed plugins on start

.github/ISSUE_TEMPLATE/0_bug_report.yml
Resolved a typographical error where "vission" was incorrectly spelled. Updated it to "vision".
=> fix: corrected typo in "vission" to "vision"

src/components/audioPlayer/index.js, src/components/audioPlayer/style.scss, src/lib/editorFile.js, src/lib/editorManager.js, src/lib/main.js, src/lib/openFile.js, src/lib/saveState.js, src/lib/showFileInfo.js, src/pages/problems/problems.js, src/plugins/sdcard/src/android/SDcard.java, src/styles/main.scss, src/views/file-info.hbs, src/views/file-menu.hbs
This PR introduces significant enhancements to the editor tab, including the ability to render HTML elements in tabs, improved media handling, and new APIs for plugin development. It also includes exception handling for SD card operations.  
1. **Custom Editor Tab**  
- Added support to render HTML elements in a custom tab
2. **Media Handlers in Editor Tabs**  
- Integrated handlers to display images, audio, and video directly in the editor tab, eliminating the need for popups.  
- Image handling supports zoom and drag functionalities.  
- Videos and audio are seamlessly rendered within the tab.  
3. **Exposed API for Plugins**  
- Introduced an API for plugins to create custom tabs with customizable icons, content, and behavior. Example:  
```js
const EditorFile = …
```
=> Implement custom editor tabs support 

src/components/audioPlayer/index.js, src/plugins/browser/android/com/foxdebug/browser/Browser.java
=> fix: fallback to */* when accept attribute is absent in input type="file"

src/plugins/browser/android/com/foxdebug/browser/Browser.java
Fixes 2nd issue of #919 
- check and automatically re-inject/show the console if previously toggled.
=> fix(browser): re-show console on page reload

src/lib/showFileInfo.js, src/styles/fileInfo.scss, src/views/file-info.hbs
Preview(with catppuccin mocha theme):
=> feat: improved file info dialog box design

src/ace/commands.js, src/components/palette/index.js, src/lib/commands.js, src/palettes/changeTheme/index.js, src/palettes/changeTheme/style.scss
- fix: palette not opening from existing palette 
- added command for changing themes
=> feat: add command to change app and editor theme from command palette

CHANGELOG.md, src/pages/plugin/plugin.js, src/pages/plugin/plugin.view.js, src/pages/plugins/plugins.js, src/sidebarApps/extensions/index.js
- fix: plugin page issue by properly handling changelogs and keywords 
- fix: infinite scroll while searching 
- feat: add option to install plugins from sidebar
=> Patch plugin page issues

src/components/palette/index.js, src/palettes/changeTheme/index.js
=> fix: palette chaining with compatibility

biome.json, src/lib/loadPlugins.js, src/lib/main.js
Ref: #1106 
- load themes plugin on acode startup and load others after successfully starting acode
- some minor biome config changes
=> feat: improve plugin loading

src/components/sidebar/index.js, src/components/sidebar/style.scss, src/lib/auth.js, src/lib/main.js, src/sidebarApps/index.js
=> feat: inapp acode account login

src/plugins/browser/android/com/foxdebug/browser/Browser.java
This pr implements download support in the browser activity
Closes #1151
Example:
=> Download support

src/lib/acode.js, src/lib/fileTypeHandler.js, src/lib/openFile.js, www/index.html
This PR introduces a file type handler system that allows plugins to register custom handlers for specific file types. This enables plugins to provide specialized viewers or editors for different file formats (e.g., PDF viewers, image editors, etc.).
- Plugins can register handlers for specific file extensions
- "Text Editor" always available as fallback option
```js
acode.registerFileHandler({
id: 'my-pdf-viewer-id',
extensions: ['pdf'],
async handleFile({ name, uri, fs, options }) {
// Handler implementation
}
});
=> Add Custom File Type Handler API

src/lib/editorFile.js
This PR introduces a major architectural change in how non-editor tabs are rendered and styled in Acode, implementing Shadow DOM isolation for better encapsulation and avoid conflicts.
- Non-editor tabs now use Shadow DOM encapsulation
- Direct DOM manipulation of tab content may not work as before
- Global styles no longer automatically affect tab content
- Plugin stylesheets need to be explicitly declared
- `addStyle(style: string)`: Add stylesheet to tab's shadow DOM
- New options in EditorFile constructor:
```typescript
interface FileOptions {
// ... existing options ...
stylesheets?: string | string[]; // URLs or CSS strings
}
```
```javascript
const tab = new EditorFile("Custom Tab", {
type: "page",
content: myElement
});
// Global styles affected the content …
```
=> feat(tabs): Implement Shadow DOM isolation for non-editor tabs

src/pages/changelog/changelog.js, src/pages/changelog/style.scss
- by default only show releases notes of installed version
- menu to select and read `latest`, `beta`, etc release notes
- linkify the mentions and pr number similar to github
=> feat: improve changelogs page

src/dialogs/select.js
This pr refactor the `Select` dialog code and add new features.  
- Support Object Items _(should be implemented in all dialogs)_.
- Checkbox  
Should we deprecate the support of array in items? And keep only Object and Sting only in future? Because it's seems not practical.
=> Refactor, feat: Select dialog

src/dialogs/select.js, src/lib/recents.js
- Added `tail` property in select box to add tail elements like `x` for deleting
- Fixed issues related to event handling
- Fixed issues started due to some missing code(followup for #1275 )
- Added `x` icon in select box to delete recent files/folder(Fixes: #1130)
- Also sanitize the html before adding to dom
=> Fixed select box issue and improved it

src/components/sidebar/style.scss, src/lib/openFolder.js, src/sidebarApps/files/index.js, src/sidebarApps/files/style.scss, src/styles/list.scss
- removed menu icon
- file tree is now horizontally scrollable when there is long file names
- added indent guide in file tree
Closes: #898 , #774 , #696
=> feat: revamped file tree

src/lib/run.js
**Note:** If your HTML file is not inside an opened project folder, it can only access files in the same folder or below it  not outside.
* Let's say your HTML file is at:
`/sdcard/HelloWorld/html/index.html`
---
✅ **Case 1: You open `/sdcard/HelloWorld` as the project folder**
* Now the HTML file **can access**:
* `/sdcard/HelloWorld/css/style.css`
* `/sdcard/HelloWorld/images/logo.png`
* `/sdcard/HelloWorld/html/scripts/app.js`
* But it **cannot access**:
* `/sdcard/AnotherFolder/data.json`
(because it's outside the project root)
---
❌ **Case 2: No folder is opened in the sidebar or a different folder is opened (just the HTML file)**
* Now the root becomes `/sdcard/HelloWorld/html`, so the HTML file **can only access**:
* `/sdcard/HelloWorld/html/scripts/app.js`
* …
=> Fix html content access

src/lib/commands.js
Fixes: https://github.com/Acode-Foundation/Acode/issues/1009#issuecomment-2939504348
Changes based on https://github.com/Acode-Foundation/Acode/commit/9a825890ce98de8f5419f51d7bbf6f2e88994c30#diff-12ff7f0e737a86da8319460b3e8eefa377543bf78c753bf614ef826233d83476L414-R432
=> Fix renaming current Termux URI file whilst viewing/editing it

src/lib/saveState.js
Files opened with `SAFMode="single"` are accessed via a SAF intent, which provides only temporary access to their URIs. Saving the state for these files can cause issues on the next app startup, as the temporary access is revoked and the app will be unable to access the file again. This change prevents saving the state for such files, avoiding potential errors and other related issues.
=> fix: don't save state of SAFMode="single" files

src/pages/plugin/plugin.js, src/pages/plugins/plugins.js
- Refactor onInstall to accept the full plugin object instead of just pluginId.
- Prevent duplicate entries in installed list and DOM.
- Fixes issues where plugins installed via search/filter/direct URL would not appear or just appending default in installed list until page reload.
---
=> fix: plugin passing undefined to plugin item on plugin page

src/dialogs/select.js, src/settings/formatterSettings.js
The "None" option in the select dialog was unclickable because the click handler was prematurely returning when the item's value was falsy. This affected options with a `null` value, such as the "None" option for formatters.
This commit modifies the click handler to allow `null` values to be selected. The handler now only returns early if the item's value is `undefined`.
Also when selected `None` on formatters settings then delete the key saved in settings for that language, as it is not require in case of `null`
=> fix: Make "None" option clickable in select dialog on formatter settings

config.xml, package.json, src/lang/en-us.json, src/plugins/system/android/com/foxdebug/system/System.java, src/plugins/system/www/plugin.js, src/plugins/terminal/plugin.xml, src/settings/terminalSettings.js, utils/storage_manager.mjs, www/index.html
This PR fixes the 'Permission Denied' issue when accessing /sdcard and /storage/emulated/0 in terminal
Note:
The Play Store might reject this (don't blame me 🙃)
=> All file access permission for terminal

src/pages/plugins/item.js, src/pages/plugins/plugins.js, src/pages/plugins/plugins.scss, src/sidebarApps/extensions/index.js, src/sidebarApps/extensions/style.scss
- fixed layout issue
- enable/disable state update issue
- dont show switch on updates page
- infinite scroll when filtering
- similar filter improvements to sidebar plugins tab
=> refactor: plugins page

src/components/terminal/terminal.js
Terminal is useless for plugins if we cannot connect to custom axs ports
=> Custom port support in Terminal manager

src/handlers/quickTools.js, src/lib/openFile.js, src/lib/searchHistory.js, src/utils/encodings.js
Fixes: #1169 
**Demo**
https://github.com/user-attachments/assets/eed59414-d0f6-4a74-9bea-6773c3d0a775
=> feat: add terminal like search and replace history

src/lib/fonts.js, src/pages/fontManager/fontManager.js, src/sidebarApps/extensions/style.scss
- fix: load custom fonts on restart
- fix: input placement on extension tab sidebar
=> fix: load custom fonts on restart

src/components/contextmenu/style.scss, src/components/searchbar/style.scss, src/components/sidebar/style.scss, src/components/tile/style.scss, src/dialogs/style.scss, src/main.scss, src/pages/plugins/plugins.scss, src/sidebarApps/extensions/style.scss, src/styles/list.scss, src/styles/page.scss
=> fix ui issue

src/pages/themeSetting/themeSetting.js
=> fix: disable changing editor theme when system is selected

src/utils/encodings.js
=> fix: encoding detection

src/components/collapsableList.js, src/components/contextmenu/style.scss, src/components/searchbar/style.scss, src/components/sidebar/index.js, src/components/sidebar/style.scss, src/components/tile/style.scss, src/dialogs/style.scss, src/lib/openFolder.js, src/main.js, src/main.scss, src/pages/plugins/plugins.scss, src/pages/sponsors/style.scss, src/pages/themeSetting/themeSetting.js, src/sidebarApps/extensions/index.js, src/sidebarApps/extensions/style.scss, src/sidebarApps/searchInFiles/index.js, src/styles/list.scss, src/styles/page.scss, src/styles/wideScreen.scss, webpack.config.js
Changes:
- Fix big screen UI
- Sidebar plugin app UI
- Global search UI
- Fix worker not loading in global search
- Code cleanup
=> fix: big screen ui and global search worker issue

build-extras.gradle, package-lock.json, package.json, src/plugins/sftp/plugin.xml, src/plugins/sftp/src/com/foxdebug/sftp/Sftp.java
Fixes #1289 , And original https://github.com/Acode-Foundation/Acode/issues/674
The issue can be more clearly visible in the logcat of Android/ADB:
```java.io.IOException: Ed25519 KeyFactory not available``` 
Leading to Errors ```
Invalid passphrase for key file
com.sshtools.common.publickey.InvalidPassphraseException: Ed25519 KeyFactory not available```
This Pull updates BC to atleast `1.79` (that's a little higher than maverick ssh client's one) while maintaining combability to not BREAK the ssh or sftp client Library.
Attempting to fix those issues mentioned above.
I'll try creating an Issue/inform on maverick after this Pull Request.
=> Fix: ED25519 SSH keys not working

.github/workflows/community-release-notifier.yml, .github/workflows/nightly-build.yml, .github/workflows/on-demand-preview-releases-PR.yml
This pull request introduces a comprehensive set of CI workflows to support nightly builds and on-demand preview releases for pull requests.
- Adds .github/workflows/nightly-build.yml for scheduled, tag-based, and workflow_call triggered nightly builds, including support for PR-triggered builds with custom version labeling.
- Adds .github/workflows/on-demand-preview-releases-PR.yml to enable maintainers and contributors to trigger preview builds for PRs using labels, with automated PR comments and label management.
- Adds .github/workflows/community-release-notifier.yml for Discord notifications on new releases.
- Ensures secrets management for keystore and build configuration, artifact upload, versioning, and clean-up steps. Required secrets: KEYSTORE_CONTENT, BUILD_JSON_CONTENT, …
=> CI: Nightly Builds

src/plugins/terminal/src/android/AlpineDocumentProvider.java
Implements the renameDocument method in AlpineDocumentProvider, allowing documents to be renamed. Also updates document flags to indicate rename support.
=> Add support for renaming documents in provider
